apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdb-sentiment-analysis
  labels:
    app: imdb-sentiment-analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imdb-sentiment-analysis
  template:
    metadata:
      labels:
        app: imdb-sentiment-analysis
    spec:
      containers:
      - name: imdb-sentiment-analysis
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/imdb-sentiment-analysis:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: DAGSHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: dagshub-secret
              key: DAGSHUB_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: imdb-sentiment-analysis-service
spec:
  type: LoadBalancer
  selector:
    app: imdb-sentiment-analysis
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000